export const DATABASE_TABLES = {
  MODULES: 'modules',
  ROLES: 'roles',
  ROLE_ADMIN_MODULES: 'role_admin_modules',
  USERS: 'users',
  LOGIN_LOGS: 'login_logs',
  COUNTRIES: 'countries',
  PROBLEMS: 'problems',
  PROBLEM_TRANSLATIONS: 'problem_translation',
  SERVICES: 'services',
  SERVICE_TRANSLATIONS: 'service_translation',
  PRODUCTS: 'products',
  PRODUCT_TRANSLATIONS: 'product_translation',
  ASTROLOGERS: 'astrologers',
  ASTROLOGER_TRANSLATIONS: 'astrologers_translations',
  ASTROLOGER_RATINGS: 'astrologer_ratings',
  ASTROLOGER_CONSULTATIONS: 'astrologer_consultations',
  ASTROLOGER_CONSULT_COUNTS: 'astrologer_consult_counts',
  ENQUIRIES: 'enquiries',
  ENQUIRY_ASSIGNMENTS: 'enquiry_assignments',
  FOLLOW_UPS: 'follow_ups',
  CUSTOMER_PAYMENTS: 'customer_payment',
  PAYMENT_LOGS: 'payment_logs',
  SUPPORT_REQUESTS: 'support_requests',
  SITE_CONTENT: 'site_content',
} as const;

export const DATABASE_CONSTANTS = DATABASE_TABLES;
