import { BRAND } from '@/lib/brand';

export const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://shreesamriddhiastro.com';

export const seoKeywords = [
  BRAND.name,
  '24x7 astrologer session',
  '24x7 astrology consultation',
  '24x7 horoscope reading',
  '24x7 kundli reading',
  'accurate annual horoscope',
  'accurate antardasha prediction',
  'accurate ascendant reading',
  'accurate birth chart reading',
  'accurate d10 chart reading',
  'accurate d9 chart reading',
  'accurate daily horoscope',
  'accurate dasha analysis',
  'accurate gemstone consultation',
  'accurate horoscope reading',
  'accurate janam kundli analysis',
  'accurate jupiter transit reading',
  'accurate ketu transit reading',
  'accurate kp astrology reading',
  'accurate kundli reading',
  'accurate lagna chart reading',
  'accurate mahadasha analysis',
  'accurate monthly horoscope',
  'accurate moon sign reading',
  'accurate muhurat consultation',
  'accurate nadi astrology reading',
  'accurate navamsa chart reading',
  'accurate numerology reading',
  'accurate palm reading',
  'accurate panchang reading',
  'accurate rahu transit reading',
  'accurate saturn transit reading',
  'accurate sun sign reading',
  'accurate tarot reading',
  'accurate transit prediction',
  'accurate varshphal reading',
  'accurate vastu consultation',
  'accurate vedic astrology reading',
  'accurate weekly horoscope',
  'accurate yearly horoscope',
  'affordable astrology consultation online',
  'affordable astrology session',
  'affordable birth chart analysis',
  'affordable horoscope matching',
  'affordable kundli reading',
  'angarak yog consultation',
  'angarak yog remedy',
  'angarak yog solution astrology',
  'annual horoscope',
  'antardasha prediction',
  'aquarius career prediction',
  'aquarius compatibility',
  'aquarius finance prediction',
  'aquarius health prediction',
  'aquarius horoscope 2026',
  'aquarius horoscope today',
  'aquarius love prediction',
  'aquarius marriage prediction',
  'aquarius monthly horoscope',
  'aquarius weekly horoscope',
  'aquarius yearly forecast',
  'aries career prediction',
  'aries compatibility',
  'aries finance prediction',
  'aries health prediction',
  'aries horoscope 2026',
  'aries horoscope today',
  'aries love prediction',
  'aries marriage prediction',
  'aries monthly horoscope',
  'aries weekly horoscope',
  'aries yearly forecast',
  'arranged marriage astrology consultation',
  'arranged marriage horoscope prediction',
  'arranged marriage problem solution astrology',
  'ascendant reading',
  'astrologer for arranged marriage',
  'astrologer for breakup',
  'astrologer for business',
  'astrologer for business expansion',
  'astrologer for business growth',
  'astrologer for business loss',
  'astrologer for business partnership',
  'astrologer for career',
  'astrologer for career guidance',
  'astrologer for child future',
  'astrologer for childbirth',
  'astrologer for childbirth timing',
  'astrologer for childless couples',
  'astrologer for court case',
  'astrologer for court cases',
  'astrologer for debt problems',
  'astrologer for divorce',
  'astrologer for divorce advice',
  'astrologer for education',
  'astrologer for exam success',
  'astrologer for family',
  'astrologer for finance',
  'astrologer for financial growth',
  'astrologer for financial problems',
  'astrologer for foreign settlement',
  'astrologer for foreign travel',
  'astrologer for government job',
  'astrologer for health',
  'astrologer for health issues',
  'astrologer for house purchase',
  'astrologer for in laws problems',
  'astrologer for inheritance',
  'astrologer for investment',
  'astrologer for job change',
  'astrologer for job stability',
  'astrologer for land dispute',
  'astrologer for legal dispute',
  'astrologer for loan approval',
  'astrologer for love',
  'astrologer for love marriage',
  'astrologer for love problems',
  'astrologer for marriage',
  'astrologer for marriage compatibility',
  'astrologer for marriage delay',
  'astrologer for marriage problems',
  'astrologer for new business idea',
  'astrologer for overseas job',
  'astrologer for partnership dispute',
  'astrologer for pregnancy',
  'astrologer for promotion',
  'astrologer for promotion delay',
  'astrologer for property',
  'astrologer for property dispute',
  'astrologer for property issues',
  'astrologer for relationship',
  'astrologer for reunion',
  'astrologer for reunion with ex',
  'astrologer for salary hike',
  'astrologer for second marriage',
  'astrologer for spouse compatibility',
  'astrologer for stock market',
  'astrologer for study abroad',
  'astrologer for visa',
  'astrologer for visa approval',
  'astrologer for will and property',
  'astrologer near me',
  'astrology app',
  'astrology consultation for India clients',
  'astrology consultation for USA clients',
  'astrology consultation for adults',
  'astrology consultation over phone',
  'astrology consultation over video call',
  'astrology consultation over whatsapp',
  'astrology consultation without app download',
  'astrology decision timing guidance',
  'astrology for NRI',
  'astrology for auspicious time for business',
  'astrology for auspicious time for marriage',
  'astrology for auspicious time for travel',
  'astrology for best time for surgery',
  'astrology for best time to buy property',
  'astrology for best time to start new job',
  'astrology for business launch muhurat',
  'astrology for business start prediction',
  'astrology for career change prediction',
  'astrology for childbirth prediction',
  'astrology for clarity in business',
  'astrology for clarity in career',
  'astrology for clarity in family matters',
  'astrology for clarity in relationships',
  'astrology for confidence in decisions',
  'astrology for engagement date',
  'astrology for entrepreneurs',
  'astrology for griha pravesh muhurat',
  'astrology for job change prediction',
  'astrology for marriage muhurat',
  'astrology for marriage timing prediction',
  'astrology for naming ceremony muhurat',
  'astrology for promotion timing',
  'astrology for property purchase timing',
  'astrology for real life decisions',
  'astrology for students',
  'astrology for travel muhurat',
  'astrology for wedding date selection',
  'astrology for working professionals',
  'astrology helpline',
  'astrology prediction',
  'astrology remedies',
  'astrology services',
  'astrology website',
  'auspicious time for business',
  'auspicious time for marriage',
  'auspicious time for travel',
  'authentic astrologer online',
  'authentic astrology advisor',
  'authentic astrology consultant',
  'authentic astrology guide',
  'authentic horoscope expert',
  'authentic kundli expert',
  'authentic vedic astrologer',
  'best astrologer for arranged marriage',
  'best astrologer for breakup',
  'best astrologer for business',
  'best astrologer for business expansion',
  'best astrologer for business loss',
  'best astrologer for business partnership',
  'best astrologer for career',
  'best astrologer for child future',
  'best astrologer for childbirth',
  'best astrologer for childless couples',
  'best astrologer for court case',
  'best astrologer for debt problems',
  'best astrologer for divorce',
  'best astrologer for education',
  'best astrologer for exam success',
  'best astrologer for family',
  'best astrologer for finance',
  'best astrologer for financial growth',
  'best astrologer for foreign travel',
  'best astrologer for government job',
  'best astrologer for health',
  'best astrologer for health issues',
  'best astrologer for house purchase',
  'best astrologer for in laws problems',
  'best astrologer for inheritance',
  'best astrologer for investment',
  'best astrologer for job change',
  'best astrologer for job stability',
  'best astrologer for land dispute',
  'best astrologer for legal dispute',
  'best astrologer for loan approval',
  'best astrologer for love',
  'best astrologer for love marriage',
  'best astrologer for marriage',
  'best astrologer for marriage compatibility',
  'best astrologer for marriage delay',
  'best astrologer for new business idea',
  'best astrologer for overseas job',
  'best astrologer for partnership dispute',
  'best astrologer for pregnancy',
  'best astrologer for promotion',
  'best astrologer for promotion delay',
  'best astrologer for property',
  'best astrologer for property dispute',
  'best astrologer for relationship',
  'best astrologer for reunion',
  'best astrologer for salary hike',
  'best astrologer for second marriage',
  'best astrologer for spouse compatibility',
  'best astrologer for stock market',
  'best astrologer for study abroad',
  'best astrologer for visa',
  'best astrologer for will and property',
  'best astrologer in Ahmedabad',
  'best astrologer in Atlanta',
  'best astrologer in Bangalore',
  'best astrologer in Boston',
  'best astrologer in California',
  'best astrologer in Canada',
  'best astrologer in Chennai',
  'best astrologer in Chicago',
  'best astrologer in Dallas',
  'best astrologer in Delhi',
  'best astrologer in Florida',
  'best astrologer in Houston',
  'best astrologer in Hyderabad',
  'best astrologer in India',
  'best astrologer in Jaipur',
  'best astrologer in Kolkata',
  'best astrologer in London',
  'best astrologer in Los Angeles',
  'best astrologer in Lucknow',
  'best astrologer in Michigan',
  'best astrologer in Mumbai',
  'best astrologer in New Jersey',
  'best astrologer in New York',
  'best astrologer in Pune',
  'best astrologer in San Francisco',
  'best astrologer in Seattle',
  'best astrologer in Texas',
  'best astrologer in Toronto',
  'best astrologer in UK',
  'best astrologer in USA',
  'best astrologer in United States',
  'best astrologer in Virginia',
  'best astrologer in Washington DC',
  'best astrologer online',
  'best astrology advisor',
  'best astrology consultant',
  'best astrology guide',
  'best horoscope expert',
  'best kundli expert',
  'best time for surgery',
  'best time to buy property',
  'best time to start new job',
  'best vedic astrologer',
  'birth chart reading',
  'book astrologer online',
  'breakup astrology consultation',
  'breakup horoscope prediction',
  'breakup problem solution astrology',
  'budget astrology consultation online',
  'budget astrology session',
  'budget birth chart analysis',
  'budget horoscope matching',
  'budget kundli reading',
  'business astrology consultation',
  'business expansion astrology consultation',
  'business expansion horoscope prediction',
  'business expansion problem solution astrology',
  'business horoscope prediction',
  'business launch muhurat',
  'business loss astrology consultation',
  'business loss horoscope prediction',
  'business loss problem solution astrology',
  'business partnership astrology consultation',
  'business partnership horoscope prediction',
  'business partnership problem solution astrology',
  'business problem solution astrology',
  'business start prediction',
  'call astrologer for advice',
  'call astrologer session',
  'call astrology consultation',
  'call horoscope reading',
  'call kundli reading',
  'cancer career prediction',
  'cancer compatibility',
  'cancer finance prediction',
  'cancer health prediction',
  'cancer horoscope 2026',
  'cancer horoscope today',
  'cancer love prediction',
  'cancer marriage prediction',
  'cancer monthly horoscope',
  'cancer weekly horoscope',
  'cancer yearly forecast',
  'capricorn career prediction',
  'capricorn compatibility',
  'capricorn finance prediction',
  'capricorn health prediction',
  'capricorn horoscope 2026',
  'capricorn horoscope today',
  'capricorn love prediction',
  'capricorn marriage prediction',
  'capricorn monthly horoscope',
  'capricorn weekly horoscope',
  'capricorn yearly forecast',
  'career astrology consultation',
  'career change prediction',
  'career horoscope prediction',
  'career problem solution astrology',
  'certified astrologer online',
  'certified astrology advisor',
  'certified astrology consultant',
  'certified astrology guide',
  'certified horoscope expert',
  'certified kundli expert',
  'certified vedic astrologer',
  'chandra dosh consultation',
  'chandra dosh remedy',
  'chandra dosh solution astrology',
  'chat astrologer session',
  'chat astrology consultation',
  'chat horoscope reading',
  'chat kundli reading',
  'chat with astrologer online',
  'child future astrology consultation',
  'child future horoscope prediction',
  'child future problem solution astrology',
  'childbirth astrology consultation',
  'childbirth horoscope prediction',
  'childbirth prediction',
  'childbirth problem solution astrology',
  'childless couples astrology consultation',
  'childless couples horoscope prediction',
  'childless couples problem solution astrology',
  'confidential astrology consultation',
  'court case astrology consultation',
  'court case horoscope prediction',
  'court case problem solution astrology',
  'd10 chart reading',
  'd9 chart reading',
  'daily horoscope',
  'daily rashifal',
  'dasha analysis',
  'debt problems astrology consultation',
  'debt problems horoscope prediction',
  'debt problems problem solution astrology',
  'dhanu rashi career prediction',
  'dhanu rashi compatibility',
  'dhanu rashi finance prediction',
  'dhanu rashi health prediction',
  'dhanu rashi horoscope 2026',
  'dhanu rashi horoscope today',
  'dhanu rashi love prediction',
  'dhanu rashi marriage prediction',
  'dhanu rashi monthly horoscope',
  'dhanu rashi weekly horoscope',
  'dhanu rashi yearly forecast',
  'discounted astrology consultation online',
  'discounted astrology session',
  'discounted birth chart analysis',
  'discounted horoscope matching',
  'discounted kundli reading',
  'divorce astrology consultation',
  'divorce horoscope prediction',
  'divorce problem solution astrology',
  'education astrology consultation',
  'education horoscope prediction',
  'education problem solution astrology',
  'engagement date',
  'exam success astrology consultation',
  'exam success horoscope prediction',
  'exam success problem solution astrology',
  'experienced astrologer online',
  'experienced astrology advisor',
  'experienced astrology consultant',
  'experienced astrology guide',
  'experienced horoscope expert',
  'experienced kundli expert',
  'experienced vedic astrologer',
  'expert astrologer online',
  'expert astrology advisor',
  'expert astrology consultant',
  'expert astrology guide',
  'expert horoscope expert',
  'expert kundli expert',
  'expert vedic astrologer',
  'family astrology consultation',
  'family horoscope prediction',
  'family problem solution astrology',
  'famous astrologer online',
  'famous astrology advisor',
  'famous astrology consultant',
  'famous astrology guide',
  'famous horoscope expert',
  'famous kundli expert',
  'famous vedic astrologer',
  'finance astrology consultation',
  'finance horoscope prediction',
  'finance problem solution astrology',
  'financial growth astrology consultation',
  'financial growth horoscope prediction',
  'financial growth problem solution astrology',
  'five star astrologer online',
  'five star astrology advisor',
  'five star astrology consultant',
  'five star astrology guide',
  'five star horoscope expert',
  'five star kundli expert',
  'five star vedic astrologer',
  'foreign travel astrology consultation',
  'foreign travel horoscope prediction',
  'foreign travel problem solution astrology',
  'free annual horoscope',
  'free antardasha prediction',
  'free ascendant reading',
  'free astrology consultation online',
  'free astrology session',
  'free birth chart analysis',
  'free birth chart reading',
  'free d10 chart reading',
  'free d9 chart reading',
  'free daily horoscope',
  'free dasha analysis',
  'free gemstone consultation',
  'free horoscope matching',
  'free horoscope reading',
  'free janam kundli',
  'free janam kundli analysis',
  'free jupiter transit reading',
  'free ketu transit reading',
  'free kp astrology reading',
  'free kundli matching',
  'free kundli reading',
  'free lagna chart reading',
  'free mahadasha analysis',
  'free monthly horoscope',
  'free moon sign reading',
  'free muhurat consultation',
  'free nadi astrology reading',
  'free navamsa chart reading',
  'free numerology reading',
  'free palm reading',
  'free panchang reading',
  'free rahu transit reading',
  'free saturn transit reading',
  'free sun sign reading',
  'free tarot reading',
  'free transit prediction',
  'free varshphal reading',
  'free vastu consultation',
  'free vedic astrology reading',
  'free weekly horoscope',
  'free yearly horoscope',
  'future prediction astrology',
  'gemini career prediction',
  'gemini compatibility',
  'gemini finance prediction',
  'gemini health prediction',
  'gemini horoscope 2026',
  'gemini horoscope today',
  'gemini love prediction',
  'gemini marriage prediction',
  'gemini monthly horoscope',
  'gemini weekly horoscope',
  'gemini yearly forecast',
  'gemstone consultation',
  'gemstone for career success',
  'gemstone for marriage',
  'gemstone recommendation astrology',
  'genuine astrologer online',
  'genuine astrology advisor',
  'genuine astrology consultant',
  'genuine astrology guide',
  'genuine astrology predictions',
  'genuine horoscope expert',
  'genuine kundli expert',
  'genuine vedic astrologer',
  'government job astrology consultation',
  'government job horoscope prediction',
  'government job problem solution astrology',
  'graha dosh consultation',
  'graha dosh remedy',
  'graha dosh solution astrology',
  'grahan dosh consultation',
  'grahan dosh remedy',
  'grahan dosh solution astrology',
  'griha pravesh muhurat',
  'grounded astrology reading',
  'guru chandal dosh remedy consultation',
  'guru chandal dosh remedy remedy',
  'guru chandal dosh remedy solution astrology',
  'guru chandal yog consultation',
  'guru chandal yog remedy',
  'guru chandal yog solution astrology',
  'health astrology consultation',
  'health horoscope prediction',
  'health issues astrology consultation',
  'health issues horoscope prediction',
  'health issues problem solution astrology',
  'health problem solution astrology',
  'highly rated astrologer online',
  'highly rated astrology advisor',
  'highly rated astrology consultant',
  'highly rated astrology guide',
  'highly rated horoscope expert',
  'highly rated kundli expert',
  'highly rated vedic astrologer',
  'horoscope matching for marriage',
  'horoscope matching service in Ahmedabad',
  'horoscope matching service in Atlanta',
  'horoscope matching service in Bangalore',
  'horoscope matching service in Boston',
  'horoscope matching service in California',
  'horoscope matching service in Canada',
  'horoscope matching service in Chennai',
  'horoscope matching service in Chicago',
  'horoscope matching service in Dallas',
  'horoscope matching service in Delhi',
  'horoscope matching service in Florida',
  'horoscope matching service in Houston',
  'horoscope matching service in Hyderabad',
  'horoscope matching service in India',
  'horoscope matching service in Jaipur',
  'horoscope matching service in Kolkata',
  'horoscope matching service in London',
  'horoscope matching service in Los Angeles',
  'horoscope matching service in Lucknow',
  'horoscope matching service in Michigan',
  'horoscope matching service in Mumbai',
  'horoscope matching service in New Jersey',
  'horoscope matching service in New York',
  'horoscope matching service in Pune',
  'horoscope matching service in San Francisco',
  'horoscope matching service in Seattle',
  'horoscope matching service in Texas',
  'horoscope matching service in Toronto',
  'horoscope matching service in UK',
  'horoscope matching service in USA',
  'horoscope matching service in United States',
  'horoscope matching service in Virginia',
  'horoscope matching service in Washington DC',
  'horoscope reading',
  'house purchase astrology consultation',
  'house purchase horoscope prediction',
  'house purchase problem solution astrology',
  'how to improve my finances business',
  'how to improve my finances career',
  'how to improve my finances court case',
  'how to improve my finances family disputes',
  'how to improve my finances health',
  'how to improve my finances job search',
  'how to improve my finances love',
  'how to improve my finances marriage',
  'how to improve my finances money problems',
  'how to improve my finances relationship issues',
  'how to overcome business',
  'how to overcome career',
  'how to overcome court case',
  'how to overcome family disputes',
  'how to overcome health',
  'how to overcome job search',
  'how to overcome love',
  'how to overcome marriage',
  'how to overcome money problems',
  'how to overcome relationship issues',
  'how to remove angarak yog',
  'how to remove business',
  'how to remove career',
  'how to remove chandra dosh',
  'how to remove court case',
  'how to remove family disputes',
  'how to remove graha dosh',
  'how to remove grahan dosh',
  'how to remove guru chandal dosh remedy',
  'how to remove guru chandal yog',
  'how to remove health',
  'how to remove job search',
  'how to remove kaal sarp dosh',
  'how to remove kemdrum yog',
  'how to remove kuja dosh',
  'how to remove love',
  'how to remove mangal dosh remedy',
  'how to remove manglik dosha',
  'how to remove marriage',
  'how to remove money problems',
  'how to remove nadi dosh',
  'how to remove pitra dosh',
  'how to remove rahu ketu remedies',
  'how to remove relationship issues',
  'how to remove sade sati',
  'how to remove shani dosh',
  'how to remove shrapit dosh',
  'how to remove vish yog',
  'how to solve business',
  'how to solve career',
  'how to solve court case',
  'how to solve family disputes',
  'how to solve health',
  'how to solve job search',
  'how to solve love',
  'how to solve marriage',
  'how to solve money problems',
  'how to solve relationship issues',
  'in laws problems astrology consultation',
  'in laws problems horoscope prediction',
  'in laws problems problem solution astrology',
  'inheritance astrology consultation',
  'inheritance horoscope prediction',
  'inheritance problem solution astrology',
  'instant astrologer session',
  'instant astrology consultation',
  'instant horoscope reading',
  'instant kundli reading',
  'investment astrology consultation',
  'investment horoscope prediction',
  'investment problem solution astrology',
  'janam kundli analysis',
  'janam kundli by date of birth and time',
  'job change astrology consultation',
  'job change horoscope prediction',
  'job change prediction',
  'job change problem solution astrology',
  'job stability astrology consultation',
  'job stability horoscope prediction',
  'job stability problem solution astrology',
  'jupiter transit reading',
  'kaal sarp dosh consultation',
  'kaal sarp dosh remedy',
  'kaal sarp dosh solution astrology',
  'kanya rashi career prediction',
  'kanya rashi compatibility',
  'kanya rashi finance prediction',
  'kanya rashi health prediction',
  'kanya rashi horoscope 2026',
  'kanya rashi horoscope today',
  'kanya rashi love prediction',
  'kanya rashi marriage prediction',
  'kanya rashi monthly horoscope',
  'kanya rashi weekly horoscope',
  'kanya rashi yearly forecast',
  'kark rashi career prediction',
  'kark rashi compatibility',
  'kark rashi finance prediction',
  'kark rashi health prediction',
  'kark rashi horoscope 2026',
  'kark rashi horoscope today',
  'kark rashi love prediction',
  'kark rashi marriage prediction',
  'kark rashi monthly horoscope',
  'kark rashi weekly horoscope',
  'kark rashi yearly forecast',
  'kemdrum yog consultation',
  'kemdrum yog remedy',
  'kemdrum yog solution astrology',
  'ketu transit reading',
  'kp astrology consultation',
  'kp astrology reading',
  'kuja dosh consultation',
  'kuja dosh remedy',
  'kuja dosh solution astrology',
  'kumbh rashi career prediction',
  'kumbh rashi compatibility',
  'kumbh rashi finance prediction',
  'kumbh rashi health prediction',
  'kumbh rashi horoscope 2026',
  'kumbh rashi horoscope today',
  'kumbh rashi love prediction',
  'kumbh rashi marriage prediction',
  'kumbh rashi monthly horoscope',
  'kumbh rashi weekly horoscope',
  'kumbh rashi yearly forecast',
  'kundli dosh analysis',
  'kundli reading',
  'kundli reading online',
  'kundli reading service in Ahmedabad',
  'kundli reading service in Atlanta',
  'kundli reading service in Bangalore',
  'kundli reading service in Boston',
  'kundli reading service in California',
  'kundli reading service in Canada',
  'kundli reading service in Chennai',
  'kundli reading service in Chicago',
  'kundli reading service in Dallas',
  'kundli reading service in Delhi',
  'kundli reading service in Florida',
  'kundli reading service in Houston',
  'kundli reading service in Hyderabad',
  'kundli reading service in India',
  'kundli reading service in Jaipur',
  'kundli reading service in Kolkata',
  'kundli reading service in London',
  'kundli reading service in Los Angeles',
  'kundli reading service in Lucknow',
  'kundli reading service in Michigan',
  'kundli reading service in Mumbai',
  'kundli reading service in New Jersey',
  'kundli reading service in New York',
  'kundli reading service in Pune',
  'kundli reading service in San Francisco',
  'kundli reading service in Seattle',
  'kundli reading service in Texas',
  'kundli reading service in Toronto',
  'kundli reading service in UK',
  'kundli reading service in USA',
  'kundli reading service in United States',
  'kundli reading service in Virginia',
  'kundli reading service in Washington DC',
  'lagna chart reading',
  'lal kitab consultation',
  'land dispute astrology consultation',
  'land dispute horoscope prediction',
  'land dispute problem solution astrology',
  'legal dispute astrology consultation',
  'legal dispute horoscope prediction',
  'legal dispute problem solution astrology',
  'leo career prediction',
  'leo compatibility',
  'leo finance prediction',
  'leo health prediction',
  'leo horoscope 2026',
  'leo horoscope today',
  'leo love prediction',
  'leo marriage prediction',
  'leo monthly horoscope',
  'leo weekly horoscope',
  'leo yearly forecast',
  'libra career prediction',
  'libra compatibility',
  'libra finance prediction',
  'libra health prediction',
  'libra horoscope 2026',
  'libra horoscope today',
  'libra love prediction',
  'libra marriage prediction',
  'libra monthly horoscope',
  'libra weekly horoscope',
  'libra yearly forecast',
  'live astrologer chat',
  'live session astrologer session',
  'live session astrology consultation',
  'live session horoscope reading',
  'live session kundli reading',
  'loan approval astrology consultation',
  'loan approval horoscope prediction',
  'loan approval problem solution astrology',
  'love astrology consultation',
  'love horoscope prediction',
  'love marriage astrology consultation',
  'love marriage horoscope prediction',
  'love marriage problem solution astrology',
  'love problem solution astrology',
  'low cost astrology consultation online',
  'low cost astrology session',
  'low cost birth chart analysis',
  'low cost horoscope matching',
  'low cost kundli reading',
  'mahadasha analysis',
  'makar rashi career prediction',
  'makar rashi compatibility',
  'makar rashi finance prediction',
  'makar rashi health prediction',
  'makar rashi horoscope 2026',
  'makar rashi horoscope today',
  'makar rashi love prediction',
  'makar rashi marriage prediction',
  'makar rashi monthly horoscope',
  'makar rashi weekly horoscope',
  'makar rashi yearly forecast',
  'mangal dosh remedy consultation',
  'mangal dosh remedy remedy',
  'mangal dosh remedy solution astrology',
  'manglik dosha consultation',
  'manglik dosha remedy',
  'manglik dosha solution astrology',
  'marriage astrology consultation',
  'marriage compatibility astrology consultation',
  'marriage compatibility horoscope prediction',
  'marriage compatibility problem solution astrology',
  'marriage delay astrology consultation',
  'marriage delay horoscope prediction',
  'marriage delay problem solution astrology',
  'marriage horoscope prediction',
  'marriage muhurat',
  'marriage prediction by date of birth',
  'marriage problem solution astrology',
  'marriage timing prediction',
  'meen rashi career prediction',
  'meen rashi compatibility',
  'meen rashi finance prediction',
  'meen rashi health prediction',
  'meen rashi horoscope 2026',
  'meen rashi horoscope today',
  'meen rashi love prediction',
  'meen rashi marriage prediction',
  'meen rashi monthly horoscope',
  'meen rashi weekly horoscope',
  'meen rashi yearly forecast',
  'mesh rashi career prediction',
  'mesh rashi compatibility',
  'mesh rashi finance prediction',
  'mesh rashi health prediction',
  'mesh rashi horoscope 2026',
  'mesh rashi horoscope today',
  'mesh rashi love prediction',
  'mesh rashi marriage prediction',
  'mesh rashi monthly horoscope',
  'mesh rashi weekly horoscope',
  'mesh rashi yearly forecast',
  'mithun rashi career prediction',
  'mithun rashi compatibility',
  'mithun rashi finance prediction',
  'mithun rashi health prediction',
  'mithun rashi horoscope 2026',
  'mithun rashi horoscope today',
  'mithun rashi love prediction',
  'mithun rashi marriage prediction',
  'mithun rashi monthly horoscope',
  'mithun rashi weekly horoscope',
  'mithun rashi yearly forecast',
  'monthly horoscope',
  'monthly rashifal',
  'moon sign reading',
  'muhurat consultation',
  'muhurat for business start',
  'muhurat for griha pravesh',
  'muhurat for marriage',
  'muhurat for naming ceremony',
  'nadi astrology consultation',
  'nadi astrology reading',
  'nadi dosh consultation',
  'nadi dosh remedy',
  'nadi dosh solution astrology',
  'naming ceremony muhurat',
  'navamsa chart reading',
  'new business idea astrology consultation',
  'new business idea horoscope prediction',
  'new business idea problem solution astrology',
  'numerology consultation',
  'numerology reading',
  'one on one astrologer session',
  'one on one astrology consultation',
  'one on one horoscope reading',
  'one on one kundli reading',
  'online annual horoscope',
  'online antardasha prediction',
  'online arranged marriage astrology reading',
  'online ascendant reading',
  'online astrologer session',
  'online astrology consultation',
  'online astrology consultation Ahmedabad',
  'online astrology consultation Atlanta',
  'online astrology consultation Bangalore',
  'online astrology consultation Boston',
  'online astrology consultation California',
  'online astrology consultation Canada',
  'online astrology consultation Chennai',
  'online astrology consultation Chicago',
  'online astrology consultation Dallas',
  'online astrology consultation Delhi',
  'online astrology consultation Florida',
  'online astrology consultation Houston',
  'online astrology consultation Hyderabad',
  'online astrology consultation India',
  'online astrology consultation Jaipur',
  'online astrology consultation Kolkata',
  'online astrology consultation London',
  'online astrology consultation Los Angeles',
  'online astrology consultation Lucknow',
  'online astrology consultation Michigan',
  'online astrology consultation Mumbai',
  'online astrology consultation New Jersey',
  'online astrology consultation New York',
  'online astrology consultation Pune',
  'online astrology consultation San Francisco',
  'online astrology consultation Seattle',
  'online astrology consultation Texas',
  'online astrology consultation Toronto',
  'online astrology consultation UK',
  'online astrology consultation USA',
  'online astrology consultation United States',
  'online astrology consultation Virginia',
  'online astrology consultation Washington DC',
  'online birth chart reading',
  'online breakup astrology reading',
  'online business astrology reading',
  'online business expansion astrology reading',
  'online business loss astrology reading',
  'online business partnership astrology reading',
  'online career astrology reading',
  'online child future astrology reading',
  'online childbirth astrology reading',
  'online childless couples astrology reading',
  'online court case astrology reading',
  'online d10 chart reading',
  'online d9 chart reading',
  'online daily horoscope',
  'online dasha analysis',
  'online debt problems astrology reading',
  'online divorce astrology reading',
  'online education astrology reading',
  'online exam success astrology reading',
  'online family astrology reading',
  'online finance astrology reading',
  'online financial growth astrology reading',
  'online foreign travel astrology reading',
  'online gemstone consultation',
  'online government job astrology reading',
  'online health astrology reading',
  'online health issues astrology reading',
  'online horoscope reading',
  'online house purchase astrology reading',
  'online in laws problems astrology reading',
  'online inheritance astrology reading',
  'online investment astrology reading',
  'online janam kundli analysis',
  'online job change astrology reading',
  'online job stability astrology reading',
  'online jupiter transit reading',
  'online ketu transit reading',
  'online kp astrology reading',
  'online kundli reading',
  'online lagna chart reading',
  'online land dispute astrology reading',
  'online legal dispute astrology reading',
  'online loan approval astrology reading',
  'online love astrology reading',
  'online love marriage astrology reading',
  'online mahadasha analysis',
  'online marriage astrology reading',
  'online marriage compatibility astrology reading',
  'online marriage delay astrology reading',
  'online monthly horoscope',
  'online moon sign reading',
  'online muhurat consultation',
  'online nadi astrology reading',
  'online navamsa chart reading',
  'online new business idea astrology reading',
  'online numerology reading',
  'online overseas job astrology reading',
  'online palm reading',
  'online panchang reading',
  'online partnership dispute astrology reading',
  'online pregnancy astrology reading',
  'online promotion astrology reading',
  'online promotion delay astrology reading',
  'online property astrology reading',
  'online property dispute astrology reading',
  'online rahu transit reading',
  'online relationship astrology reading',
  'online reunion astrology reading',
  'online salary hike astrology reading',
  'online saturn transit reading',
  'online second marriage astrology reading',
  'online spouse compatibility astrology reading',
  'online stock market astrology reading',
  'online study abroad astrology reading',
  'online sun sign reading',
  'online tarot reading',
  'online transit prediction',
  'online varshphal reading',
  'online vastu consultation',
  'online vedic astrology reading',
  'online visa astrology reading',
];

export const defaultSeo = {
  title: `${BRAND.name} | Online Astrology Consultations`,
  description:
    'Book a private online astrology consultation for love, career, business, family, kundli, and birth chart guidance with Shree Samriddhi Astro.',
  keywords: seoKeywords,
};
